name: Run Other Actions

on:
  workflow_run:
    workflows: ["Versioning"]
    types:
      - completed

jobs:
  other_tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}

      - name: Run other tasks
        run: |
          echo "Running other tasks after version bump..."
