name: Show Last Commit Message

on:
  push:
    branches:
      - main

jobs:
  display_commit_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the last commit message
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Last commit message: $LAST_COMMIT_MESSAGE"
