name: Show Last Commit Message

on:
  push:
    branches:
      - main

jobs:
  display_commit_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the last commit message
        id: get_last_commit
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "LAST_COMMIT_MESSAGE=$LAST_COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Check commit message and exit if not 'UPDATE'
        id: check_commit_message
        run: |
          if [[ "${LAST_COMMIT_MESSAGE}" != *"UPDATE"* ]]; then
            echo "Commit message does not contain 'UPDATE'. Exiting."
            exit 0
          fi

      - name: Display last commit message
        if: ${{ env.LAST_COMMIT_MESSAGE == 'UPDATE' }}
        run: echo "Last commit message: ${{ env.LAST_COMMIT
