name: Show Last Commit Message

on:
  push:
    branches:
      - main

jobs:
  display_commit_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the last commit message
        id: get_last_commit
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Check commit message and exit if not 'UPDATE'
        id: check_commit_message
        run: |
          if [[ "${{ steps.get_last_commit.outputs.message }}" != *"UPDATE"* ]]; then
            echo "Commit message does not contain 'UPDATE'. Exiting."
            exit 0
          fi

      - name: Display last commit message
        if: contains(steps.get_last_commit.outputs.message, 'UPDATE')
        run: echo "Last commit message: ${{ steps.get_last_commit.outputs.message }}"
