name: Versioning

on:
  push:
    branches:
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get the last commit message
        id: get_last_commit
        run: echo "LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Exit if version bump
        if: contains(steps.get_last_commit.outputs.LAST_COMMIT_MESSAGE, 'Bump version to')
        run: exit 0

      - name: Get the current version
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Bump version
        id: bump_version
        run: |
          VERSION=$(echo $VERSION | awk -F. '{$3+=1; OFS="."; print $1,$2,$3}')
          echo "New version: $VERSION"
          echo $VERSION > version.txt
          jq '.version = "'$VERSION'"' composer.json > composer.json.tmp && mv composer.json.tmp composer.json

      - name: Commit and push changes
        run: |
          git add version.txt composer.json
          git commit -m "Bump version to $VERSION"
          git tag -a "v$VERSION" -m "Version $VERSION"
          git push origin --tags
          git push
