name: Show Last Commit Message

on:
  push:
    branches:
      - main  # Change to your desired branch

jobs:
  display-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get last commit message
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "LAST_COMMIT_MSG=$LAST_COMMIT_MSG" >> $GITHUB_ENV
      
      - name: Display last commit message
        run: echo "Last commit message: $LAST_COMMIT_MSG"
